### ISSUE TITLE
Result not rendered. 

### ISSUE THREAD

**Issue by afidegnum** [apache/incubator-age-viewer#20]
**Describe the bug**
while following the build, and run procedure, after `npm run start` I encountered the following error: 
```

Compiled with warnings.

Compiled with warnings.

src/components/cypherresult/containers/CypherResultCytoscapeContainer.js
  Line 35:7:  Unexpected console statement  no-console

src/components/cytoscape/CypherResultCytoscapeChart.jsx
  Line 117:7:  Unexpected alert  no-alert

src/components/cytoscape/CytoscapeStyleSheet.js
  Line 63:7:  Unexpected unnamed method 'background-color'    func-names
  Line 65:7:  Unexpected unnamed method 'border-color'        func-names
  Line 72:7:  Unexpected unnamed method 'text-max-width'      func-names
  Line 97:7:  Unexpected unnamed method 'line-color'          func-names
  Line 98:7:  Unexpected unnamed method 'target-arrow-color'  func-names

src/components/frame/presentations/CypherGraphResultFrame.jsx
  Line 95:7:   Unexpected alert  no-alert
  Line 111:7:  Unexpected alert  no-alert
  Line 126:7:  Unexpected alert  no-alert
  Line 142:7:  Unexpected alert  no-alert

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

Error: Not connected
    at _callee3$ (/home/afidegnum/Documents/incubator-age-viewer/backend/src/controllers/databaseController.js:54:19)
    at tryCatch (/home/afidegnum/Documents/incubator-age-viewer/backend/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/afidegnum/Documents/incubator-age-viewer/backend/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/afidegnum/Documents/incubator-age-viewer/backend/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/afidegnum/Documents/incubator-age-viewer/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/afidegnum/Documents/incubator-age-viewer/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/afidegnum/Documents/incubator-age-viewer/backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
info: ::ffff:127.0.0.1 - - [02/Feb/2022:07:02:33 +0000] "GET /api/v1/db HTTP/1.1" 500 51
 {"timestamp":"2022-02-02 07:02:33"}
```

The database and the graph are corrected all right but no result was rendered after running the edge queries. 

here is the screenshot of the issue. 

![image](https://user-images.githubusercontent.com/374206/152109194-7e47225c-d080-4072-bbf7-c28aa9b96f36.png)

**Comment by afidegnum** [comment]
```
info: ::ffff:127.0.0.1 - - [02/Feb/2022:07:02:33 +0000] "GET /api/v1/db HTTP/1.1" 500 51
 {"timestamp":"2022-02-02 07:02:33"}
Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/home/afidegnum/Documents/incubator-age-viewer/backend/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (events.js:421:28)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:467:12)
    at Socket.<anonymous> (/home/afidegnum/Documents/incubator-age-viewer/backend/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at TCP.<anonymous> (net.js:673:12)
info: ::ffff:127.0.0.1 - - [02/Feb/2022:07:04:56 +0000] "POST /api/v1/db/connect HTTP/1.1" 500 85
 {"timestamp":"2022-02-02 07:04:56"}
info: ::ffff:127.0.0.1 - - [02/Feb/2022:07:05:07 +0000] "POST /api/v1/db/connect HTTP/1.1" 200 130
 {"timestamp":"2022-02-02 07:05:07"}
info: ::ffff:127.0.0.1 - - [02/Feb/2022:07:05:07 +0000] "GET /api/v1/db/meta HTTP/1.1" 304 -
 {"timestamp":"2022-02-02 07:05:07"}
info: ::ffff:127.0.0.1 - - [02/Feb/2022:07:05:08 +0000] "GET /api/v1/db/metaChart HTTP/1.1" 500 2
 {"timestamp":"2022-02-02 07:05:08"}
info: ::ffff:127.0.0.1 - - [02/Feb/2022:07:05:20 +0000] "POST /api/v1/cypher HTTP/1.1" 200 59
 {"timestamp":"2022-02-02 07:05:20"}

```

**Comment by afidegnum** [comment]
Everything works right now.
